/**
 * 🦄 FULL AUTO CEO - ROBÍM VŠETKO ZA TEBA
 * Automaticky generuje, commitne, pushne, deployne
 * Spustenie: node FULL_AUTO_CEO.js
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const cron = require('node-cron');

const POSTS_FOLDER = path.join(__dirname, '..', 'generated-posts');
const PROJECT_ROOT = path.join(__dirname, '..');

if (!fs.existsSync(POSTS_FOLDER)) {
    fs.mkdirSync(POSTS_FOLDER, { recursive: true });
}

const POST_TEMPLATES = [
    {
        emoji: '🦄⏰',
        title: 'POSLEDNÉ HODINY',
        body: `€50 cena platí len DNES.\n\nZajtra: €200\nPozajtra: Dvere zatvorené\n\n10 miest. 24 hodín.\n\nfordfofer.vercel.app/links`,
        hashtags: '#FordFofer #LastChance #Urgency #Investment #AICapital #Money'
    },
    {
        emoji: '🦄📊',
        title: 'UPDATE',
        body: `Prvých 5 investorov už vstúpilo.\n\nPrečo?\n\nLebo vedia že:\n• AI je budúcnosť\n• Skorý vstup = najväčší výnos\n• €50 dnes = €200 zajtra\n\nfordfofer.vercel.app/links`,
        hashtags: '#FOMO #FordFofer #EarlyBird #Investment #Money'
    },
    {
        emoji: '🦄🔥',
        title: 'HOT TAKE',
        body: `95% traderov by NEMALO obchodovať.\n\nPrečo?\n\nEmócie. Strach. Chamtivosť.\n\nAI nepozná ani jedno z týchto slov.\n\n€50 = Lifetime prístup.\n\nfordfofer.vercel.app/links`,
        hashtags: '#UnpopularOpinion #FordFofer #AItrading #NoEmotions #Money'
    },
    {
        emoji: '🦄💰',
        title: 'ČO ZÍSKAŠ ZA €50',
        body: `→ AI agenty 24/7\n→ Zero chyba\n→ $1.2B kapacita\n→ Lifetime prístup\n\nČo stratíš ak čakáš?\n€150 (cena stúpne)\n\nfordfofer.vercel.app/links`,
        hashtags: '#Value #FordFofer #ROI #SmartInvestment #Money'
    },
    {
        emoji: '🦄🚀',
        title: 'POSLEDNÉ MIESTA',
        body: `€50 = Lifetime prístup k $1.2B AI systému.\n\nČo získaš:\n→ AI agenty 24/7\n→ Zero chyba\n→ Early investor status\n\nZostáva 10 miest.\n\nfordfofer.vercel.app/links`,
        hashtags: '#FordFofer #AICapital #Investment #Slovakia #Startup'
    },
    {
        emoji: '🦄⚡',
        title: 'MATEMATIKA JE JASNÁ',
        body: `AI pracuje 24/7.\nTy spíš 8 hodín.\n\nKto zarobí viac?\n\n€50 vstup. Lifetime prístup.\n\nfordfofer.vercel.app/links`,
        hashtags: '#AItrading #FordFofer #PassiveIncome #SmartMoney'
    }
];

function generatePost() {
    const template = POST_TEMPLATES[Math.floor(Math.random() * POST_TEMPLATES.length)];
    return {
        text: `${template.emoji} ${template.title}\n\n${template.body}\n\n${template.hashtags}`,
        emoji: template.emoji,
        title: template.title
    };
}

function savePost(post) {
    const timestamp = new Date();
    const dateStr = timestamp.toISOString().split('T')[0];
    const timeStr = timestamp.toTimeString().split(' ')[0].replace(/:/g, '-');
    
    const filename = `post-${dateStr}-${timeStr}.txt`;
    const filepath = path.join(POSTS_FOLDER, filename);
    
    const content = `╔═══════════════════════════════════════════════════════════════╗
║  🦄 POST VYGENEROVANÝ: ${timestamp.toLocaleString('sk-SK')}
║  🤖 AUTO-GENERATED BY FULL AUTO CEO
╚═══════════════════════════════════════════════════════════════╝

${post.text}

╔═══════════════════════════════════════════════════════════════╝
║  📋 SKOPÍRUJ TEXT VYŠŠIE A POSTNI NA INSTAGRAM!
║  💾 Súbor: ${filename}
╚═══════════════════════════════════════════════════════════════╝
`;
    
    fs.writeFileSync(filepath, content, 'utf8');
    
    console.log(`\n✅ POST VYGENEROVANÝ: ${filename}`);
    console.log(`📁 ${filepath}\n`);
    
    // Otvor súbor
    try {
        execSync(`start notepad "${filepath}"`, { cwd: PROJECT_ROOT });
    } catch (e) {
        // Ignore errors
    }
    
    return filepath;
}

function autoCommit() {
    try {
        console.log('\n💾 AUTO-COMMITTING...');
        execSync('git add -A', { cwd: PROJECT_ROOT, stdio: 'inherit' });
        
        const timestamp = new Date().toLocaleString('sk-SK');
        execSync(`git commit -m "Auto-generated post: ${timestamp}"`, { 
            cwd: PROJECT_ROOT, 
            stdio: 'inherit' 
        });
        
        console.log('✅ COMMITTED\n');
    } catch (e) {
        console.log('⚠️ Commit skipped (no changes or git error)\n');
    }
}

function autoDeploy() {
    try {
        console.log('🚀 AUTO-DEPLOYING...');
        execSync('npx vercel --prod --yes', { 
            cwd: PROJECT_ROOT, 
            stdio: 'inherit',
            timeout: 60000 
        });
        console.log('✅ DEPLOYED\n');
    } catch (e) {
        console.log('⚠️ Deploy skipped (timeout or error)\n');
    }
}

function doFullCycle() {
    console.log('\n' + '═'.repeat(60));
    console.log('🦄 FULL AUTO CEO - CYKLUS ZAČÍNA');
    console.log('═'.repeat(60));
    
    // 1. Generuj post
    const post = generatePost();
    const filepath = savePost(post);
    
    // 2. Commit
    autoCommit();
    
    // 3. Deploy (každý 3. cyklus)
    if (Math.random() > 0.66) {
        autoDeploy();
    }
    
    console.log('✅ CYKLUS UKONČENÝ\n');
}

// Spusti prvý cyklus
doFullCycle();

// Automaticky každé 2 hodiny
cron.schedule('0 */2 * * *', () => {
    doFullCycle();
});

// Automaticky každý deň o 8:00
cron.schedule('0 8 * * *', () => {
    console.log('\n🌅 RANNÝ POST GENERUJEM...\n');
    doFullCycle();
});

// Automaticky každý deň o 20:00
cron.schedule('0 20 * * *', () => {
    console.log('\n🌙 VEČERNÝ POST GENERUJEM...\n');
    doFullCycle();
});

console.log(`
╔═══════════════════════════════════════════════════════════════╗
║     🦄 FULL AUTO CEO - BEŽÍ NA POZADÍ                          ║
║                                                                ║
║     ✅ Generuje posty každé 2 hodiny                          ║
║     ✅ Commitne automaticky                                   ║
║     ✅ Deployne pravidelne                                    ║
║     ✅ Všetko sa robí za teba!                                ║
║                                                                ║
║     Stlač Ctrl+C pre ukončenie                                ║
╚═══════════════════════════════════════════════════════════════╝
`);

console.log('✅ Systém beží! Teraz len čakaj a posty prichádzajú automaticky!\n');


